"""Stateless Vulnerability Detail Report compiler (ADR 0007).

`compile_vdt_report` is a pure function of source artifacts plus explicit
operator inputs. It does not read or write the event store, so the same
artifacts, evaluations, package configuration, and `--as-of` instant produce the
same bytes on every run. It fails closed: an artifact that does not ingest, a
vulnerability with no detection time, or an evaluation that matches nothing
stops the run with diagnostics and no output.
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from complyroll import __version__
from complyroll.adapters import DiagnosticLevel, ingest_stig_artifact
from complyroll.correlation import VulnerabilityGroup, correlate_observations
from complyroll.models import CaseStatus, Observation, PainRating, ResourceRef
from complyroll.policy import (
    CertificationClass,
    CertificationProfile,
    PolicyDeadline,
    PolicyProvenance,
    SelectedPolicy,
    load_bundled_rule_source_snapshot,
    select_policy,
)
from complyroll.policy.source import RuleSourceSnapshot
from complyroll.schemas import (
    ReportSchema,
    SchemaProvenance,
    SchemaValidationResult,
    load_bundled_schema_bundle,
    validate_bundled_report,
)

from .evaluations import EvaluationInput, EvaluationSet, ReportInputError

DISCLAIMER = (
    "Generated by ComplyRoll; informational; not a FedRAMP® determination; "
    "the provider remains responsible for compliance with the FedRAMP Consolidated "
    "Rules for 2026."
)
EXTENSION_KEY = "x-complyroll"
GENERATOR_NAME = "complyroll"

#: ADR 0007 Decision 4. `accepted` never appears in a Vulnerability Detail Report.
FINAL_DISPOSITIONS: dict[CaseStatus, str] = {
    CaseStatus.PARTIALLY_MITIGATED: "Partially Mitigated",
    CaseStatus.FULLY_MITIGATED: "Fully Mitigated",
    CaseStatus.REMEDIATED: "Fully Mitigated",
    CaseStatus.FALSE_POSITIVE: "False Positive",
}
ACTIVE_STATUSES = frozenset(
    {CaseStatus.NEW, CaseStatus.EVALUATING, CaseStatus.ACTIVE}
)

_EVALUATION_RULE = "VER-TFR-EVU"
_RESPONSE_RULE = "VDR-TFR-PVR"
_ACCEPTANCE_RULE = "VER-TFR-MAV"


@dataclass(frozen=True, slots=True)
class ReportDiagnostic:
    """One machine-readable note about a compile run."""

    level: DiagnosticLevel
    code: str
    message: str
    location: str | None = None

    def render(self) -> str:
        """Return the single-line form used on stderr."""

        text = f"{self.level.value}: {self.code}: {self.message}"
        if self.location:
            text = f"{text} [{self.location}]"
        return text

    def to_dict(self) -> dict[str, str]:
        value = {"level": self.level.value, "code": self.code, "message": self.message}
        if self.location:
            value["location"] = self.location
        return value


class ReportCompileError(Exception):
    """Compilation stopped; no report was produced."""

    def __init__(self, diagnostics: Sequence[ReportDiagnostic]) -> None:
        self.diagnostics: tuple[ReportDiagnostic, ...] = tuple(diagnostics)
        summary = "; ".join(item.message for item in self.diagnostics[:3])
        suffix = "" if len(self.diagnostics) <= 3 else f"; plus {len(self.diagnostics) - 3} more"
        super().__init__(f"report compilation failed: {summary}{suffix}")


@dataclass(frozen=True, slots=True)
class ReportOptions:
    """Explicit package configuration for one compile run (Decision 5)."""

    certification_class: CertificationClass
    package_uri: str
    period_from: datetime
    period_to: datetime
    as_of: datetime
    calendar_timezone: str = "UTC"
    detected_at_attestation: datetime | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.certification_class, CertificationClass):
            raise TypeError("certification_class must be a CertificationClass")
        _require_absolute_http_uri(self.package_uri)
        for value, name in (
            (self.period_from, "period_from"),
            (self.period_to, "period_to"),
            (self.as_of, "as_of"),
        ):
            _require_aware(value, name)
        if self.period_from > self.period_to:
            raise ValueError("period_from must not be after period_to")
        if self.detected_at_attestation is not None:
            _require_aware(self.detected_at_attestation, "detected_at_attestation")
        # Constructing the profile validates the calendar timezone at the boundary.
        CertificationProfile(
            self.certification_class,
            calendar_timezone=self.calendar_timezone,
        )

    @property
    def profile(self) -> CertificationProfile:
        """Return the certification profile these options select."""

        return CertificationProfile(
            self.certification_class,
            calendar_timezone=self.calendar_timezone,
        )


@dataclass(frozen=True, slots=True)
class CompiledDeadline:
    """One policy clock computed for a vulnerability, with its provenance inputs."""

    rule_id: str
    rule_name: str
    force: str
    anchor: str
    start_at: datetime
    due_at: datetime
    timeframe_amount: int | str
    timeframe_unit: str
    satisfied: bool

    def to_dict(self) -> dict[str, Any]:
        return {
            "ruleId": self.rule_id,
            "ruleName": self.rule_name,
            "force": self.force,
            "anchor": self.anchor,
            "startAt": _iso(self.start_at),
            "dueAt": _iso(self.due_at),
            "timeframe": {"amount": self.timeframe_amount, "unit": self.timeframe_unit},
        }


@dataclass(frozen=True, slots=True)
class CompiledArtifact:
    """One ingested source artifact and what it contributed."""

    name: str
    sha256: str
    parser: str
    parser_version: str
    size_bytes: int
    observation_count: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "sha256": self.sha256,
            "parser": self.parser,
            "parserVersion": self.parser_version,
            "sizeBytes": self.size_bytes,
        }


@dataclass(frozen=True, slots=True)
class CompiledVulnerability:
    """The normalized record both renderers read (README non-negotiable rule 5)."""

    tracking_id: str
    source_type: str
    source_record_id: str
    context_key: str
    description: str
    detected_at: datetime
    detected_at_source: str
    detection_source: str
    observation_ids: tuple[str, ...]
    resources: tuple[ResourceRef, ...]
    source_identifiers: tuple[str, ...]
    deadlines: tuple[CompiledDeadline, ...]
    is_overdue: bool
    overdue_explanation: str
    evaluation: EvaluationInput | None = None
    final_disposition: str | None = None
    remediated: bool = False
    status: CaseStatus | None = None

    @property
    def is_evaluated(self) -> bool:
        return self.evaluation is not None

    @property
    def current_rating(self) -> PainRating | None:
        return self.evaluation.pain if self.evaluation is not None else None

    @property
    def next_due(self) -> CompiledDeadline | None:
        """Return the earliest deadline this vulnerability has not yet satisfied."""

        pending = [item for item in self.deadlines if not item.satisfied]
        if not pending:
            return None
        return min(pending, key=lambda item: (item.due_at, item.rule_id))

    def to_official_dict(self) -> dict[str, Any]:
        """Return the official `vulnerabilityDetail` object plus the extension."""

        value: dict[str, Any] = {
            "providerTrackingId": self.tracking_id,
            "detection": {
                "detectedAt": _iso(self.detected_at),
                "detectionSource": self.detection_source,
            },
            "vulnerabilityDescription": self.description,
            "overdueStatus": self._overdue_dict(),
            EXTENSION_KEY: self._extension_dict(),
        }
        evaluation = self.evaluation
        if evaluation is not None:
            value["evaluationCompletedAt"] = _iso(evaluation.completed_at)
            value["isInternetReachable"] = evaluation.is_internet_reachable
            value["isLikelyExploitable"] = evaluation.is_likely_exploitable
            value["currentRating"] = int(evaluation.pain)
            value["potentialAgencyImpact"] = evaluation.potential_agency_impact
            if evaluation.projected_next_reduction is not None:
                value["projectedNextReduction"] = {
                    "estimatedAt": _iso(evaluation.projected_next_reduction.estimated_at),
                    "targetRating": int(evaluation.projected_next_reduction.target_rating),
                }
            if evaluation.supplementary_risk_information is not None:
                value["supplementaryRiskInformation"] = (
                    evaluation.supplementary_risk_information
                )
        if self.final_disposition is not None:
            value["finalDisposition"] = self.final_disposition
        return value

    def _overdue_dict(self) -> dict[str, Any]:
        value: dict[str, Any] = {"isOverdue": self.is_overdue}
        if self.is_overdue:
            value["explanation"] = self.overdue_explanation
        return value

    def _extension_dict(self) -> dict[str, Any]:
        evaluation = self.evaluation
        return {
            "observationIds": list(self.observation_ids),
            "resources": [
                {"resourceId": item.resource_id, "resourceType": item.resource_type}
                for item in self.resources
            ],
            "sourceIdentifiers": list(self.source_identifiers),
            "deadlines": [item.to_dict() for item in self.deadlines],
            "remediated": self.remediated,
            "painReductionEvents": [
                {"reducedAt": _iso(event.reduced_at), "rating": int(event.rating)}
                for event in (evaluation.pain_reduction_events if evaluation else ())
            ],
            "evaluator": evaluation.evaluator if evaluation else None,
            "rationale": evaluation.rationale if evaluation else None,
            "detectedAtSource": self.detected_at_source,
        }


@dataclass(frozen=True, slots=True)
class AcceptedVulnerability:
    """An accepted vulnerability, reported under VER-RPT-AVI and never in the VDT."""

    vulnerability: CompiledVulnerability
    acceptance_rationale: str


@dataclass(frozen=True, slots=True)
class ReportMetadata:
    """Everything the renderers need that is not a vulnerability record."""

    options: ReportOptions
    artifacts: tuple[CompiledArtifact, ...]
    rules_provenance: PolicyProvenance
    schema_provenance: SchemaProvenance
    generator_version: str
    parser_versions: tuple[tuple[str, str], ...]
    attestation_applied_to: tuple[str, ...] = ()

    @property
    def attestation(self) -> datetime | None:
        if not self.attestation_applied_to:
            return None
        return self.options.detected_at_attestation


@dataclass(frozen=True, slots=True)
class CompiledVdtReport:
    """One compiled report and the twin renderings built from the same records."""

    document: dict[str, Any]
    vulnerabilities: tuple[CompiledVulnerability, ...]
    accepted: tuple[AcceptedVulnerability, ...]
    diagnostics: tuple[ReportDiagnostic, ...]
    validation: SchemaValidationResult
    metadata: ReportMetadata

    def to_json(self, indent: int = 2) -> str:
        """Return the official JSON document with a stable key order."""

        return (
            json.dumps(self.document, indent=indent, sort_keys=True, ensure_ascii=False) + "\n"
        )

    def to_markdown(self) -> str:
        """Return the human-readable twin, derived from the same records."""

        return _render_markdown(self)


def compile_vdt_report(
    artifact_paths: Sequence[Path],
    *,
    options: ReportOptions,
    evaluations: EvaluationSet | None = None,
) -> CompiledVdtReport:
    """Compile one Vulnerability Detail Report from artifacts and explicit inputs."""

    if not isinstance(options, ReportOptions):
        raise TypeError("options must be a ReportOptions")
    if evaluations is not None and not isinstance(evaluations, EvaluationSet):
        raise TypeError("evaluations must be an EvaluationSet")

    diagnostics: list[ReportDiagnostic] = []
    artifacts, observations = _ingest_all(artifact_paths, options, diagnostics)

    correlation = correlate_observations(observations)
    for observation in correlation.unresolved:
        diagnostics.append(
            ReportDiagnostic(
                level=DiagnosticLevel.WARNING,
                code="unresolved_observation",
                message=(
                    f"{observation.source_record_id} on "
                    f"{observation.resource.resource_id} has disposition "
                    f"{observation.disposition.value} and was not reported as a vulnerability"
                ),
                location=observation.source_artifact_name or observation.context_key,
            )
        )

    groups = correlation.groups
    matches = _match_evaluations(groups, evaluations)

    snapshot = load_bundled_rule_source_snapshot()
    policy = select_policy(snapshot, options.profile)
    schema_provenance = _schema_provenance()

    records: list[CompiledVulnerability] = []
    accepted: list[AcceptedVulnerability] = []
    attested: list[str] = []
    missing_detection: list[str] = []

    for group in groups:
        detected_at, detected_source = _resolve_detection_time(group, options)
        if detected_at is None:
            missing_detection.append(group.tracking_id)
            continue
        if detected_source == "attestation":
            attested.append(group.tracking_id)
        record = _build_record(
            group=group,
            detected_at=detected_at,
            detected_at_source=detected_source,
            evaluation=matches.get(group.tracking_id),
            policy=policy,
            snapshot=snapshot,
            options=options,
        )
        if record.status is CaseStatus.ACCEPTED:
            evaluation = record.evaluation
            rationale = evaluation.acceptance_rationale if evaluation else None
            accepted.append(
                AcceptedVulnerability(
                    vulnerability=record,
                    acceptance_rationale=rationale or "",
                )
            )
            diagnostics.append(
                ReportDiagnostic(
                    level=DiagnosticLevel.INFO,
                    code="accepted_excluded",
                    message=(
                        f"{record.tracking_id} is an accepted vulnerability and belongs in "
                        "the VER-RPT-AVI report, not the Vulnerability Detail Report"
                    ),
                    location=record.source_record_id,
                )
            )
            continue
        records.append(record)

    if missing_detection:
        raise ReportCompileError(
            (
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="detection_time_missing",
                    message=(
                        "no source timestamp and no --detected-at attestation for: "
                        + ", ".join(sorted(missing_detection))
                    ),
                ),
            )
        )

    metadata = ReportMetadata(
        options=options,
        artifacts=tuple(artifacts),
        rules_provenance=policy.provenance,
        schema_provenance=schema_provenance,
        generator_version=__version__,
        parser_versions=_parser_versions(observations),
        attestation_applied_to=tuple(sorted(attested)),
    )
    document = _build_document(tuple(records), metadata)
    validation = validate_bundled_report(ReportSchema.VULNERABILITY_DETAIL, document)
    if not validation.is_valid:
        raise ReportCompileError(
            tuple(
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="schema_invalid",
                    message=(
                        "the compiled report failed official schema validation, which is a "
                        f"ComplyRoll defect: {issue.validator}: {issue.message}"
                    ),
                    location=issue.instance_pointer or "<root>",
                )
                for issue in validation.issues
            )
        )

    return CompiledVdtReport(
        document=document,
        vulnerabilities=tuple(records),
        accepted=tuple(accepted),
        diagnostics=tuple(diagnostics),
        validation=validation,
        metadata=metadata,
    )


def _ingest_all(
    artifact_paths: Sequence[Path],
    options: ReportOptions,
    diagnostics: list[ReportDiagnostic],
) -> tuple[list[CompiledArtifact], list[Observation]]:
    if not artifact_paths:
        raise ReportCompileError(
            (
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="no_artifacts",
                    message="at least one source artifact is required",
                ),
            )
        )

    errors: list[ReportDiagnostic] = []
    artifacts: list[CompiledArtifact] = []
    observations: list[Observation] = []
    seen_digests: set[str] = set()

    for raw_path in artifact_paths:
        path = Path(raw_path)
        result = ingest_stig_artifact(path, ingested_at=options.as_of)
        for item in result.diagnostics:
            entry = ReportDiagnostic(
                level=item.level,
                code=item.code,
                message=item.message,
                location=item.location or str(path),
            )
            if item.level is DiagnosticLevel.ERROR:
                errors.append(entry)
            else:
                diagnostics.append(entry)
        if result.errors or result.artifact is None:
            continue
        if result.artifact.digest_sha256 in seen_digests:
            diagnostics.append(
                ReportDiagnostic(
                    level=DiagnosticLevel.WARNING,
                    code="duplicate_artifact",
                    message=(
                        "identical artifact bytes were supplied more than once and the "
                        "repeat was skipped"
                    ),
                    location=result.artifact.name,
                )
            )
            continue
        seen_digests.add(result.artifact.digest_sha256)
        artifacts.append(
            CompiledArtifact(
                name=result.artifact.name,
                sha256=result.artifact.digest_sha256,
                parser=result.artifact.parser_name,
                parser_version=result.artifact.parser_version,
                size_bytes=result.artifact.size_bytes,
                observation_count=len(result.observations),
            )
        )
        observations.extend(result.observations)

    if errors:
        raise ReportCompileError(errors)
    return artifacts, observations


def _match_evaluations(
    groups: Sequence[VulnerabilityGroup],
    evaluations: EvaluationSet | None,
) -> dict[str, EvaluationInput]:
    if evaluations is None or not evaluations.entries:
        return {}
    matched: dict[str, EvaluationInput] = {}
    claimed_by: dict[str, EvaluationInput] = {}
    errors: list[ReportDiagnostic] = []

    for entry in evaluations.entries:
        candidates = [group for group in groups if _matches(entry, group)]
        if not candidates:
            errors.append(
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="evaluation_unmatched",
                    message=f"no vulnerability matches {entry.match.describe()}",
                    location=entry.location,
                )
            )
            continue
        if len(candidates) > 1:
            named = ", ".join(group.tracking_id for group in candidates)
            errors.append(
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="evaluation_ambiguous",
                    message=(
                        f"{entry.match.describe()} matches {len(candidates)} vulnerabilities "
                        f"({named}); add contextKey or sourceType"
                    ),
                    location=entry.location,
                )
            )
            continue
        group = candidates[0]
        previous = claimed_by.get(group.tracking_id)
        if previous is not None:
            errors.append(
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="evaluation_duplicate",
                    message=(
                        f"{group.tracking_id} is evaluated by both {previous.location} "
                        f"and {entry.location}"
                    ),
                    location=entry.location,
                )
            )
            continue
        claimed_by[group.tracking_id] = entry
        matched[group.tracking_id] = entry

    if errors:
        raise ReportCompileError(errors)
    return matched


def _matches(entry: EvaluationInput, group: VulnerabilityGroup) -> bool:
    if entry.match.source_record_id != group.source_record_id:
        return False
    if entry.match.context_key is not None and entry.match.context_key != group.context_key:
        return False
    return not (
        entry.match.source_type is not None and entry.match.source_type != group.source_type
    )


def _resolve_detection_time(
    group: VulnerabilityGroup,
    options: ReportOptions,
) -> tuple[datetime | None, str]:
    if group.earliest_observed_at is not None:
        return group.earliest_observed_at.astimezone(UTC), "artifact"
    if options.detected_at_attestation is not None:
        return options.detected_at_attestation.astimezone(UTC), "attestation"
    return None, "missing"


def _build_record(
    *,
    group: VulnerabilityGroup,
    detected_at: datetime,
    detected_at_source: str,
    evaluation: EvaluationInput | None,
    policy: SelectedPolicy,
    snapshot: RuleSourceSnapshot,
    options: ReportOptions,
) -> CompiledVulnerability:
    status = evaluation.resolved_status if evaluation is not None else None
    if evaluation is not None and evaluation.case_status is CaseStatus.CLOSED and status is None:
        raise ReportCompileError(
            (
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="closed_without_disposition",
                    message=(
                        f"{group.tracking_id} is closed with no recorded disposition; "
                        "supply closedDisposition"
                    ),
                    location=evaluation.location,
                ),
            )
        )

    is_accepted = status is CaseStatus.ACCEPTED
    final_disposition = None if status is None else FINAL_DISPOSITIONS.get(status)
    if status is not None and status not in ACTIVE_STATUSES and not is_accepted:
        if final_disposition is None:  # pragma: no cover - table above is exhaustive
            raise AssertionError(f"unmapped case status: {status}")
    disposition_recorded = final_disposition is not None

    deadlines, overdue_clauses = _compute_deadlines(
        detected_at=detected_at,
        evaluation=evaluation,
        policy=policy,
        options=options,
        disposition_recorded=disposition_recorded,
        acceptance_recorded=is_accepted,
    )
    explanation = ""
    if overdue_clauses:
        explanation = _explanation(overdue_clauses, policy, snapshot, options)

    tracking_id = group.tracking_id
    if evaluation is not None and evaluation.tracking_id is not None:
        tracking_id = evaluation.tracking_id

    return CompiledVulnerability(
        tracking_id=tracking_id,
        source_type=group.source_type,
        source_record_id=group.source_record_id,
        context_key=group.context_key,
        description=_describe(group),
        detected_at=detected_at,
        detected_at_source=detected_at_source,
        detection_source=group.detection_source,
        observation_ids=group.observation_ids,
        resources=group.resources,
        source_identifiers=group.source_identifiers,
        deadlines=deadlines,
        is_overdue=bool(overdue_clauses),
        overdue_explanation=explanation,
        evaluation=evaluation,
        final_disposition=final_disposition,
        remediated=status is CaseStatus.REMEDIATED,
        status=status,
    )


def _describe(group: VulnerabilityGroup) -> str:
    title = group.title.strip()
    if not title:
        return group.source_record_id
    return f"{group.source_record_id}: {title}"


def _compute_deadlines(
    *,
    detected_at: datetime,
    evaluation: EvaluationInput | None,
    policy: SelectedPolicy,
    options: ReportOptions,
    disposition_recorded: bool,
    acceptance_recorded: bool,
) -> tuple[tuple[CompiledDeadline, ...], tuple[str, ...]]:
    as_of = options.as_of
    class_name = options.certification_class.value
    deadlines: list[CompiledDeadline] = []
    clauses: list[str] = []

    evaluation_deadline = policy.evaluation_deadline(detected_at)
    evaluated = evaluation is not None
    deadlines.append(_compiled(evaluation_deadline, anchor="detection", satisfied=evaluated))
    if not evaluated and as_of > evaluation_deadline.due_at:
        clauses.append(
            f"{evaluation_deadline.rule_id} ({evaluation_deadline.force.value}, "
            f"Class {class_name}): the evaluation window opened at detection "
            f"{_iso(detected_at)} and closed {_iso(evaluation_deadline.due_at)} "
            "with no evaluation recorded."
        )

    if evaluation is None:
        return tuple(deadlines), tuple(clauses)

    resolved = disposition_recorded or acceptance_recorded
    response = policy.response_deadline(
        evaluation.completed_at,
        pain=evaluation.pain,
        is_internet_reachable=evaluation.is_internet_reachable,
        is_likely_exploitable=evaluation.is_likely_exploitable,
    )
    if response is not None:
        deadlines.append(_compiled(response, anchor="evaluation", satisfied=resolved))
        if not resolved and as_of > response.due_at:
            clauses.append(
                f"{response.rule_id} ({response.force.value}, Class {class_name}): the "
                f"response target for PAIN {evaluation.pain.name}, "
                f"{_reachability(evaluation.is_internet_reachable)}, "
                f"{_exploitability(evaluation.is_likely_exploitable)} ran from the "
                f"completed evaluation {_iso(evaluation.completed_at)} and passed "
                f"{_iso(response.due_at)} with no disposition recorded."
            )

    acceptance = policy.acceptance_deadline(evaluation.completed_at)
    deadlines.append(_compiled(acceptance, anchor="evaluation", satisfied=resolved))
    if not resolved and as_of > acceptance.due_at:
        clauses.append(
            f"{acceptance.rule_id} ({acceptance.force.value}, Class {class_name}): the "
            f"{acceptance.timeframe.display_amount}-{acceptance.timeframe.unit.value} "
            f"categorization threshold ran from the completed evaluation "
            f"{_iso(evaluation.completed_at)} and passed {_iso(acceptance.due_at)} with "
            "no disposition and no acceptance recorded."
        )
    return tuple(deadlines), tuple(clauses)


def _compiled(deadline: PolicyDeadline, *, anchor: str, satisfied: bool) -> CompiledDeadline:
    return CompiledDeadline(
        rule_id=deadline.rule_id,
        rule_name=deadline.rule_name,
        force=deadline.force.value,
        anchor=anchor,
        start_at=deadline.start_at,
        due_at=deadline.due_at,
        timeframe_amount=deadline.timeframe.display_amount,
        timeframe_unit=deadline.timeframe.unit.value,
        satisfied=satisfied,
    )


def _explanation(
    clauses: Sequence[str],
    policy: SelectedPolicy,
    snapshot: RuleSourceSnapshot,
    options: ReportOptions,
) -> str:
    parts = list(clauses)
    parts.append(f"Rules dataset commit {policy.provenance.commit}.")
    obtain = _optional_adoption_notice(snapshot, options.as_of)
    if obtain:
        parts.append(obtain)
    return " ".join(parts)


def _optional_adoption_notice(snapshot: RuleSourceSnapshot, as_of: datetime) -> str:
    dates = _obtain_dates(snapshot)
    if not dates:
        return ""
    earliest = min(dates.values())
    if as_of.astimezone(UTC).date().isoformat() >= earliest:
        return ""
    if len(set(dates.values())) == 1:
        rendered = earliest
    else:
        rendered = " and ".join(
            f"{value} ({document})" for document, value in sorted(dates.items())
        )
    return (
        "The VDR and VER rulesets are in their optional-adoption period until "
        f"{rendered}."
    )


def _obtain_dates(snapshot: RuleSourceSnapshot) -> dict[str, str]:
    data = snapshot.data
    dates: dict[str, str] = {}
    for document_id in ("VDR", "VER"):
        node: Any = data.get("FRR", {}).get(document_id, {})
        for key in ("info", "effective", "date", "obtain"):
            if not isinstance(node, dict):
                node = None
                break
            node = node.get(key)
        if isinstance(node, str) and node:
            dates[document_id] = node
    return dates


def _reachability(value: bool) -> str:
    return "internet reachable" if value else "not internet reachable"


def _exploitability(value: bool) -> str:
    return "likely exploitable" if value else "not likely exploitable"


def _parser_versions(observations: Sequence[Observation]) -> tuple[tuple[str, str], ...]:
    pairs = {(item.parser_name, item.parser_version) for item in observations}
    return tuple(sorted(pairs))


def _schema_provenance() -> SchemaProvenance:
    bundle = load_bundled_schema_bundle()
    document = bundle.document(ReportSchema.VULNERABILITY_DETAIL.value)
    return SchemaProvenance(
        repository=bundle.manifest.repository,
        commit=bundle.manifest.commit,
        schema_id=document.entry.schema_id,
        schema_version=document.entry.version,
        schema_sha256=document.content_sha256,
    )


def _build_document(
    records: Sequence[CompiledVulnerability],
    metadata: ReportMetadata,
) -> dict[str, Any]:
    options = metadata.options
    attestation: dict[str, Any] | None = None
    if metadata.attestation_applied_to and options.detected_at_attestation is not None:
        attestation = {
            "detectedAt": _iso(options.detected_at_attestation),
            "appliedTo": list(metadata.attestation_applied_to),
        }
    return {
        "certificationPackageOverviewUri": options.package_uri,
        "reportPeriod": {
            "from": _iso(options.period_from),
            "to": _iso(options.period_to),
        },
        "vulnerabilities": [record.to_official_dict() for record in records],
        EXTENSION_KEY: {
            "generator": {"name": GENERATOR_NAME, "version": metadata.generator_version},
            "generatedAt": _iso(options.as_of),
            "calendarTimezone": options.calendar_timezone,
            "certificationClass": options.certification_class.value,
            "rulesSource": {
                "repository": metadata.rules_provenance.repository,
                "commit": metadata.rules_provenance.commit,
                "datasetVersion": metadata.rules_provenance.dataset_version,
                "datasetLastUpdated": metadata.rules_provenance.dataset_last_updated,
                "sha256": metadata.rules_provenance.dataset_sha256,
            },
            "schemaSource": {
                "repository": metadata.schema_provenance.repository,
                "commit": metadata.schema_provenance.commit,
                "schemaId": metadata.schema_provenance.schema_id,
                "schemaVersion": metadata.schema_provenance.schema_version,
                "sha256": metadata.schema_provenance.schema_sha256,
            },
            "parserVersions": dict(metadata.parser_versions),
            "artifacts": [artifact.to_dict() for artifact in metadata.artifacts],
            "detectionTimeAttestation": attestation,
            "disclaimer": DISCLAIMER,
        },
    }


# --------------------------------------------------------------------------------------
# Markdown twin. Every number below comes from the compiled records, never from the JSON.
# --------------------------------------------------------------------------------------


def _render_markdown(report: CompiledVdtReport) -> str:
    metadata = report.metadata
    options = metadata.options
    records = report.vulnerabilities
    lines: list[str] = []
    write = lines.append

    write("# Vulnerability Detail Report")
    write("")
    write(f"- **Certification package:** {_cell(options.package_uri)}")
    write(f"- **Report period:** {_iso(options.period_from)} to {_iso(options.period_to)}")
    write(f"- **Certification class:** {options.certification_class.value}")
    write(f"- **Generated at:** {_iso(options.as_of)}")
    write(f"- **Calendar timezone:** {_cell(options.calendar_timezone)}")
    write("")

    write("## Provenance")
    write("")
    write("| Source | Reference | Digest |")
    write("|---|---|---|")
    rules = metadata.rules_provenance
    schema = metadata.schema_provenance
    write(
        f"| Rules dataset | {_cell(rules.repository)} at {rules.commit} "
        f"(version {_cell(rules.dataset_version)}, updated {_cell(rules.dataset_last_updated)}) "
        f"| {rules.dataset_sha256} |"
    )
    write(
        f"| Report schema | {_cell(schema.repository)} at {schema.commit} "
        f"({_cell(schema.schema_id)} version {_cell(schema.schema_version)}) "
        f"| {schema.schema_sha256} |"
    )
    write(f"| Generator | {GENERATOR_NAME} {_cell(metadata.generator_version)} | n/a |")
    write("")

    write("## Summary")
    write("")
    write("| Measure | Count |")
    write("|---|---:|")
    write(f"| Vulnerabilities reported | {len(records)} |")
    write(f"| Evaluated | {sum(1 for item in records if item.is_evaluated)} |")
    write(f"| Not yet evaluated | {sum(1 for item in records if not item.is_evaluated)} |")
    write(f"| Overdue | {sum(1 for item in records if item.is_overdue)} |")
    write(f"| Accepted, reported under VER-RPT-AVI | {len(report.accepted)} |")
    for rating in PainRating:
        count = sum(1 for item in records if item.current_rating is rating)
        write(f"| Current PAIN {rating.name} | {count} |")
    write("")

    write("## Vulnerabilities")
    write("")
    if not records:
        write("No open vulnerabilities were reported for this period.")
        write("")
    else:
        write(
            "| Tracking ID | Source record | Resources | Detected | Evaluation completed "
            "| IRV | LEV | PAIN | Next due | Overdue | Disposition |"
        )
        write("|---|---|---:|---|---|---|---|---|---|---|---|")
        for item in records:
            evaluation = item.evaluation
            next_due = item.next_due
            write(
                "| "
                + " | ".join(
                    (
                        _cell(item.tracking_id),
                        _cell(item.source_record_id),
                        str(len(item.resources)),
                        _iso(item.detected_at),
                        _iso(evaluation.completed_at) if evaluation else "n/a",
                        _flag(evaluation.is_internet_reachable) if evaluation else "n/a",
                        _flag(evaluation.is_likely_exploitable) if evaluation else "n/a",
                        item.current_rating.name if item.current_rating else "n/a",
                        (
                            f"{_iso(next_due.due_at)} ({_cell(next_due.rule_id)})"
                            if next_due
                            else "n/a"
                        ),
                        _flag(item.is_overdue),
                        _cell(item.final_disposition) if item.final_disposition else "active",
                    )
                )
                + " |"
            )
        write("")

    write("## Detection time attestation")
    write("")
    attested = metadata.attestation_applied_to
    attestation = metadata.attestation
    if attestation is None or not attested:
        write(
            "Every reported vulnerability carried a detection time from its source artifact. "
            "No attestation was needed."
        )
    else:
        write(
            f"The operator attested a detection time of {_iso(attestation)} for "
            f"{len(attested)} vulnerability record(s) whose source artifacts declare no "
            "assessment timestamp. ComplyRoll never substitutes file modification or "
            "ingestion time for a detection time."
        )
    write("")

    write("## Inputs")
    write("")
    write("| Artifact | SHA-256 | Parser | Observations |")
    write("|---|---|---|---:|")
    for artifact in metadata.artifacts:
        write(
            f"| {_cell(artifact.name)} | {artifact.sha256[:12]} | "
            f"{_cell(artifact.parser)} {_cell(artifact.parser_version)} "
            f"| {artifact.observation_count} |"
        )
    write("")

    write("## Diagnostics")
    write("")
    if not report.diagnostics:
        write("No diagnostics were raised.")
    else:
        for diagnostic in report.diagnostics:
            location = f" [{_cell(diagnostic.location)}]" if diagnostic.location else ""
            write(
                f"- **{diagnostic.level.value}** {_cell(diagnostic.code)}: "
                f"{_cell(diagnostic.message)}{location}"
            )
    write("")

    write("---")
    write("")
    write(DISCLAIMER)
    return "\n".join(lines) + "\n"


def _flag(value: bool) -> str:
    return "yes" if value else "no"


def _cell(value: str) -> str:
    """Escape one Markdown table cell the way the compatibility renderer does."""

    return (
        value.replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\r", " ")
        .replace("\n", " ")
    )


def _iso(value: datetime) -> str:
    return value.astimezone(UTC).isoformat().replace("+00:00", "Z")


def _require_aware(value: object, field_name: str) -> None:
    if not isinstance(value, datetime):
        raise TypeError(f"{field_name} must be a datetime, got {type(value).__name__}")
    if value.tzinfo is None or value.utcoffset() is None:
        raise ValueError(f"{field_name} must include a timezone")


def _require_absolute_http_uri(value: object) -> None:
    if not isinstance(value, str) or not value.strip():
        raise ValueError("package_uri must be non-blank text")
    parts = urlsplit(value)
    if parts.scheme not in {"http", "https"} or not parts.netloc:
        raise ValueError(
            "package_uri must be an absolute http or https URI, got " f"{value!r}"
        )


__all__ = [
    "ACTIVE_STATUSES",
    "DISCLAIMER",
    "EXTENSION_KEY",
    "FINAL_DISPOSITIONS",
    "AcceptedVulnerability",
    "CompiledArtifact",
    "CompiledDeadline",
    "CompiledVdtReport",
    "CompiledVulnerability",
    "ReportCompileError",
    "ReportDiagnostic",
    "ReportInputError",
    "ReportMetadata",
    "ReportOptions",
    "compile_vdt_report",
]
