"""Stateless Vulnerability Detail Report compiler (ADR 0007).

`compile_vdt_report` is a pure function of source artifacts plus explicit
operator inputs. It does not read or write the event store, so the same
artifacts, evaluations, package configuration, and `--as-of` instant produce the
same bytes on every run. It fails closed: an artifact that does not ingest, a
vulnerability with no detection time, or an evaluation that matches nothing
stops the run with diagnostics and no output.

The work splits in two (ADR 0010). `compile_record_set` turns normalized inputs
into the period-agnostic record set every report reads from, and `project_vdt`
selects and renders the Vulnerability Detail Report out of it. The other report
modules in this package project their own documents from the same record set and
share the helpers below, so one vulnerability is compiled once however many
reports describe it.
"""

from __future__ import annotations

import json
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field, replace
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Protocol
from urllib.parse import urlsplit

from complyroll import __version__
from complyroll.adapters import (
    ArtifactProvenance,
    DiagnosticLevel,
    IngestResult,
    ingest_stig_artifact,
)
from complyroll.correlation import (
    VulnerabilityGroup,
    correlate_observations,
    group_open_observations,
)
from complyroll.models import CaseStatus, Observation, PainRating, ResourceRef
from complyroll.policy import (
    CertificationClass,
    CertificationProfile,
    PolicyDeadline,
    PolicyProvenance,
    SelectedPolicy,
    load_bundled_rule_source_snapshot,
    select_policy,
)
from complyroll.policy.source import RuleSourceSnapshot
from complyroll.schemas import (
    ReportSchema,
    SchemaProvenance,
    SchemaValidationResult,
    load_bundled_schema_bundle,
    validate_bundled_report,
)

from .evaluations import EvaluationInput, EvaluationSet, ReportInputError

DISCLAIMER = (
    "Generated by ComplyRoll; informational; not a FedRAMP® determination; "
    "the provider remains responsible for compliance with the FedRAMP Consolidated "
    "Rules for 2026."
)
EXTENSION_KEY = "x-complyroll"
GENERATOR_NAME = "complyroll"

#: ADR 0007 Decision 4, amended 2026-09-04 (ADR 0009): Common Definitions 0.3.0 added
#: `Remediated` to the official enumeration. `accepted` never appears in a Vulnerability
#: Detail Report.
FINAL_DISPOSITIONS: dict[CaseStatus, str] = {
    CaseStatus.PARTIALLY_MITIGATED: "Partially Mitigated",
    CaseStatus.FULLY_MITIGATED: "Fully Mitigated",
    CaseStatus.REMEDIATED: "Remediated",
    CaseStatus.FALSE_POSITIVE: "False Positive",
}
ACTIVE_STATUSES = frozenset(
    {CaseStatus.NEW, CaseStatus.EVALUATING, CaseStatus.ACTIVE}
)

_EVALUATION_RULE = "VER-TFR-EVU"
_RESPONSE_RULE = "VDR-TFR-PVR"
_ACCEPTANCE_RULE = "VER-TFR-MAV"


@dataclass(frozen=True, slots=True)
class ReportDiagnostic:
    """One machine-readable note about a compile run."""

    level: DiagnosticLevel
    code: str
    message: str
    location: str | None = None

    def render(self) -> str:
        """Return the single-line form used on stderr."""

        text = f"{self.level.value}: {self.code}: {self.message}"
        if self.location:
            text = f"{text} [{self.location}]"
        return text

    def to_dict(self) -> dict[str, str]:
        value = {"level": self.level.value, "code": self.code, "message": self.message}
        if self.location:
            value["location"] = self.location
        return value


class ReportCompileError(Exception):
    """Compilation stopped; no report was produced."""

    def __init__(self, diagnostics: Sequence[ReportDiagnostic]) -> None:
        self.diagnostics: tuple[ReportDiagnostic, ...] = tuple(diagnostics)
        summary = "; ".join(item.message for item in self.diagnostics[:3])
        suffix = "" if len(self.diagnostics) <= 3 else f"; plus {len(self.diagnostics) - 3} more"
        super().__init__(f"report compilation failed: {summary}{suffix}")


@dataclass(frozen=True, slots=True, kw_only=True)
class ReportOptions:
    """Explicit package configuration for one compile run (Decision 5).

    The report period is optional because not every report has one (ADR 0010). The
    Vulnerability Detail Report and the Accepted Vulnerability Information report
    select by period and refuse to compile without it; the historical activity report
    is a snapshot at `as_of` and never reads it. One bound without the other is a
    mistake rather than a half-open period, so it is refused here.
    """

    certification_class: CertificationClass
    package_uri: str
    as_of: datetime
    period_from: datetime | None = None
    period_to: datetime | None = None
    calendar_timezone: str = "UTC"
    detected_at_attestation: datetime | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.certification_class, CertificationClass):
            raise TypeError("certification_class must be a CertificationClass")
        _require_absolute_http_uri(self.package_uri)
        _require_aware(self.as_of, "as_of")
        if (self.period_from is None) != (self.period_to is None):
            raise ValueError("period_from and period_to must be given together")
        if self.period_from is not None and self.period_to is not None:
            _require_aware(self.period_from, "period_from")
            _require_aware(self.period_to, "period_to")
            if self.period_from > self.period_to:
                raise ValueError("period_from must not be after period_to")
        if self.detected_at_attestation is not None:
            _require_aware(self.detected_at_attestation, "detected_at_attestation")
        # Constructing the profile validates the calendar timezone at the boundary.
        CertificationProfile(
            self.certification_class,
            calendar_timezone=self.calendar_timezone,
        )

    @property
    def has_period(self) -> bool:
        """Return whether these options carry a report period."""

        return self.period_from is not None and self.period_to is not None

    @property
    def period(self) -> tuple[datetime, datetime]:
        """Return the report period as `(from, to)`, both inclusive.

        Raises `ValueError` when the options carry no period. Report projections
        that need one call `_report_period` instead, which turns the same condition
        into a compile diagnostic.
        """

        if self.period_from is None or self.period_to is None:
            raise ValueError("these options carry no report period")
        return (self.period_from, self.period_to)

    @property
    def profile(self) -> CertificationProfile:
        """Return the certification profile these options select."""

        return CertificationProfile(
            self.certification_class,
            calendar_timezone=self.calendar_timezone,
        )


@dataclass(frozen=True, slots=True)
class DetectionAttestation:
    """Attested detection times for groups whose sources declare none.

    `default` is the stateless `--detected-at` and applies to every group that needs
    one. `by_tracking_id` carries per-case attestations read back from
    `detection.attested` events and wins over the default for the cases it names. An
    attestation never overrides a detection time a source artifact declares (ADR 0007
    amendment).
    """

    default: datetime | None = None
    by_tracking_id: Mapping[str, datetime] = field(default_factory=dict)

    def for_tracking_id(self, tracking_id: str) -> datetime | None:
        """Return the instant attested for one group, or None when none applies."""

        attested = self.by_tracking_id.get(tracking_id)
        return self.default if attested is None else attested


@dataclass(frozen=True, slots=True)
class CompiledDeadline:
    """One policy clock computed for a vulnerability, with its provenance inputs."""

    rule_id: str
    rule_name: str
    force: str
    anchor: str
    start_at: datetime
    due_at: datetime
    timeframe_amount: int | str
    timeframe_unit: str
    satisfied: bool

    def to_dict(self) -> dict[str, Any]:
        # `satisfied` is the Markdown twin's Satisfied column. Publishing the clock
        # without it left a machine reader unable to tell a met deadline from a missed
        # one while a human reader of the same report could (ADR 0007 amendment, the
        # two renderings carry the same audit content).
        return {
            "ruleId": self.rule_id,
            "ruleName": self.rule_name,
            "force": self.force,
            "anchor": self.anchor,
            "startAt": _iso(self.start_at),
            "dueAt": _iso(self.due_at),
            "satisfied": self.satisfied,
            "timeframe": {"amount": self.timeframe_amount, "unit": self.timeframe_unit},
        }


@dataclass(frozen=True, slots=True)
class CompiledArtifact:
    """One ingested source artifact and what it contributed."""

    name: str
    sha256: str
    parser: str
    parser_version: str
    size_bytes: int
    observation_count: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "sha256": self.sha256,
            "parser": self.parser,
            "parserVersion": self.parser_version,
            "sizeBytes": self.size_bytes,
            "observationCount": self.observation_count,
        }


@dataclass(frozen=True, slots=True)
class CompiledVulnerability:
    """The normalized record both renderers read (README non-negotiable rule 5)."""

    tracking_id: str
    source_type: str
    source_record_id: str
    context_key: str
    description: str
    detected_at: datetime
    detected_at_source: str
    detection_source: str
    observation_ids: tuple[str, ...]
    resources: tuple[ResourceRef, ...]
    source_identifiers: tuple[str, ...]
    deadlines: tuple[CompiledDeadline, ...]
    is_overdue: bool
    overdue_explanation: str
    evaluation: EvaluationInput | None = None
    final_disposition: str | None = None
    remediated: bool = False
    status: CaseStatus | None = None
    untimestamped_observation_ids: tuple[str, ...] = ()
    original_tracking_id: str = ""

    @property
    def is_evaluated(self) -> bool:
        return self.evaluation is not None

    @property
    def has_disposition(self) -> bool:
        """Return True when a disposition of record exists for this vulnerability."""

        return self.final_disposition is not None or self.status is CaseStatus.ACCEPTED

    @property
    def activity_instants(self) -> tuple[datetime, ...]:
        """Return every recorded activity instant, for report-period selection.

        Detection, the completed evaluation, each completed PAIN reduction, and the
        projected next reduction are the recorded activity a period can contain
        (ADR 0007 amendment, report period selects contents).
        """

        instants = [self.detected_at]
        evaluation = self.evaluation
        if evaluation is not None:
            instants.append(evaluation.completed_at)
            instants.extend(event.reduced_at for event in evaluation.pain_reduction_events)
            if evaluation.projected_next_reduction is not None:
                instants.append(evaluation.projected_next_reduction.estimated_at)
        return tuple(instants)

    @property
    def evaluation_location(self) -> str:
        """Return the evaluations-file location behind this record, if any."""

        return self.evaluation.location if self.evaluation is not None else "no evaluation entry"

    @property
    def current_rating(self) -> PainRating | None:
        return self.evaluation.pain if self.evaluation is not None else None

    @property
    def next_due(self) -> CompiledDeadline | None:
        """Return the earliest deadline this vulnerability has not yet satisfied."""

        pending = [item for item in self.deadlines if not item.satisfied]
        if not pending:
            return None
        return min(pending, key=lambda item: (item.due_at, item.rule_id))

    def to_official_dict(self) -> dict[str, Any]:
        """Return the official `vulnerabilityDetail` object plus the extension."""

        value: dict[str, Any] = {
            "providerTrackingId": self.tracking_id,
            "detection": {
                "detectedAt": _iso(self.detected_at),
                "detectionSource": self.detection_source,
            },
            "vulnerabilityDescription": self.description,
            "overdueStatus": self._overdue_dict(),
            EXTENSION_KEY: self._extension_dict(),
        }
        evaluation = self.evaluation
        if evaluation is not None:
            value["evaluationCompletedAt"] = _iso(evaluation.completed_at)
            value["isInternetReachable"] = evaluation.is_internet_reachable
            value["isLikelyExploitable"] = evaluation.is_likely_exploitable
            value["currentRating"] = int(evaluation.pain)
            value["potentialAgencyImpact"] = evaluation.potential_agency_impact
            if evaluation.projected_next_reduction is not None:
                value["projectedNextReduction"] = {
                    "estimatedAt": _iso(evaluation.projected_next_reduction.estimated_at),
                    "targetRating": int(evaluation.projected_next_reduction.target_rating),
                }
            if evaluation.supplementary_risk_information is not None:
                value["supplementaryRiskInformation"] = (
                    evaluation.supplementary_risk_information
                )
            # Official since Common Definitions 0.3.0 (ADR 0009); the extension carried
            # this list while the report schemas had no slot for it.
            if evaluation.pain_reduction_events:
                value["painReductionEvents"] = [
                    {"reducedAt": _iso(event.reduced_at), "rating": int(event.rating)}
                    for event in evaluation.pain_reduction_events
                ]
        if self.final_disposition is not None:
            value["finalDisposition"] = self.final_disposition
        return value

    def _overdue_dict(self) -> dict[str, Any]:
        value: dict[str, Any] = {"isOverdue": self.is_overdue}
        if self.is_overdue:
            value["explanation"] = self.overdue_explanation
        return value

    def _extension_dict(self) -> dict[str, Any]:
        evaluation = self.evaluation
        return {
            "observationIds": list(self.observation_ids),
            "resources": [
                {"resourceId": item.resource_id, "resourceType": item.resource_type}
                for item in self.resources
            ],
            "sourceIdentifiers": list(self.source_identifiers),
            "untimestampedObservationIds": list(self.untimestamped_observation_ids),
            "deadlines": [item.to_dict() for item in self.deadlines],
            "remediated": self.remediated,
            "evaluator": evaluation.evaluator if evaluation else None,
            "rationale": evaluation.rationale if evaluation else None,
            "detectedAtSource": self.detected_at_source,
        }


@dataclass(frozen=True, slots=True)
class AcceptedVulnerability:
    """An accepted vulnerability, reported under VER-RPT-AVI and never in the VDT."""

    vulnerability: CompiledVulnerability
    acceptance_rationale: str


@dataclass(frozen=True, slots=True)
class ReportMetadata:
    """Everything the renderers need that is not a vulnerability record."""

    options: ReportOptions
    artifacts: tuple[CompiledArtifact, ...]
    rules_provenance: PolicyProvenance
    schema_provenance: SchemaProvenance
    generator_version: str
    parser_versions: tuple[tuple[str, str], ...]
    attestation_applied_to: tuple[str, ...] = ()
    excluded_by_period: int = 0
    attestation_detected_at: datetime | None = None

    @property
    def attestation(self) -> datetime | None:
        """Return the single attested instant, or None when there is not exactly one."""

        if not self.attestation_applied_to:
            return None
        return self.attestation_detected_at


@dataclass(frozen=True, slots=True)
class CompiledVdtReport:
    """One compiled report and the twin renderings built from the same records."""

    document: dict[str, Any]
    vulnerabilities: tuple[CompiledVulnerability, ...]
    accepted: tuple[AcceptedVulnerability, ...]
    diagnostics: tuple[ReportDiagnostic, ...]
    validation: SchemaValidationResult
    metadata: ReportMetadata

    def to_json(self, indent: int = 2) -> str:
        """Return the official JSON document with a stable key order."""

        return (
            json.dumps(self.document, indent=indent, sort_keys=True, ensure_ascii=False) + "\n"
        )

    def to_markdown(self) -> str:
        """Return the human-readable twin, derived from the same records."""

        return _render_markdown(self)


class CompiledReport(Protocol):
    """What every compiled report exposes, whichever official format it projects.

    The members are read-only properties rather than attributes so that the frozen
    report dataclasses satisfy the protocol structurally; a caller that only writes
    a report out needs nothing more than these four.
    """

    @property
    def document(self) -> dict[str, Any]: ...

    @property
    def diagnostics(self) -> tuple[ReportDiagnostic, ...]: ...

    def to_json(self, indent: int = 2) -> str: ...

    def to_markdown(self) -> str: ...


def compile_vdt_report(
    artifact_paths: Sequence[Path],
    *,
    options: ReportOptions,
    evaluations: EvaluationSet | None = None,
) -> CompiledVdtReport:
    """Compile one Vulnerability Detail Report from artifacts and explicit inputs."""

    return project_vdt(
        compile_record_set_from_artifacts(artifact_paths, options=options, evaluations=evaluations)
    )


def compile_record_set_from_artifacts(
    artifact_paths: Sequence[Path],
    *,
    options: ReportOptions,
    evaluations: EvaluationSet | None = None,
) -> CompiledRecordSet:
    """Ingest artifacts, match evaluations, and compile the record set they describe.

    This is the stateless path's front half. Every report the package projects from
    the same artifacts starts here, so ingest happens once per run rather than once
    per report.
    """

    if not isinstance(options, ReportOptions):
        raise TypeError("options must be a ReportOptions")
    if evaluations is not None and not isinstance(evaluations, EvaluationSet):
        raise TypeError("evaluations must be an EvaluationSet")

    ingest_diagnostics: list[ReportDiagnostic] = []
    artifacts, observations = _ingest_all(artifact_paths, options, ingest_diagnostics)
    groups = group_open_observations(observations)
    matches = _match_evaluations(groups, evaluations)
    return compile_record_set(
        artifacts=artifacts,
        observations=observations,
        ingest_diagnostics=ingest_diagnostics,
        evaluations_by_tracking_id=matches,
        attestation=DetectionAttestation(default=options.detected_at_attestation),
        options=options,
    )


@dataclass(frozen=True, slots=True)
class CompiledRecordSet:
    """Every compiled vulnerability plus the shared provenance, before any report selects.

    The set knows nothing about report periods or which official format will read it.
    Each projection applies its own selection to `records` and appends its own
    diagnostics after the ones held here, so the diagnostics on the set are exactly
    the ones the compile itself raised: ingest diagnostics in their total order, then
    unresolved observations, then partial detection times in group order.
    """

    records: tuple[CompiledVulnerability, ...]
    artifacts: tuple[CompiledArtifact, ...]
    diagnostics: tuple[ReportDiagnostic, ...]
    rules_provenance: PolicyProvenance
    parser_versions: tuple[tuple[str, str], ...]
    generator_version: str
    options: ReportOptions


def compile_records(
    *,
    artifacts: Sequence[CompiledArtifact],
    observations: Sequence[Observation],
    ingest_diagnostics: Sequence[ReportDiagnostic],
    evaluations_by_tracking_id: Mapping[str, EvaluationInput],
    attestation: DetectionAttestation,
    options: ReportOptions,
) -> CompiledVdtReport:
    """Compile one report from already-normalized records.

    Both the stateless path and the event-sourced rebuild call this, so neither can
    drift from the other by construction (ADR 0008 Decision 5). Callers own how the
    artifacts, observations, ingest diagnostics, and evaluations were obtained;
    everything downstream of them happens here.

    The order a caller supplies its inputs in is not a fact about the package, so
    nothing it decides may reach the document. The stateless path receives artifacts
    and their ingest diagnostics in command-line order and the persisted path in
    ingest order, and both used to be published as given, which meant the same
    artifacts named in a different order compiled to different bytes. Both lists are
    put in a total order here, in the one place both paths run through, so the two
    paths cannot drift apart from each other or from their own earlier runs. Ordering
    them in either caller instead would fix one path and leave the other.
    """

    return project_vdt(
        compile_record_set(
            artifacts=artifacts,
            observations=observations,
            ingest_diagnostics=ingest_diagnostics,
            evaluations_by_tracking_id=evaluations_by_tracking_id,
            attestation=attestation,
            options=options,
        )
    )


def compile_record_set(
    *,
    artifacts: Sequence[CompiledArtifact],
    observations: Sequence[Observation],
    ingest_diagnostics: Sequence[ReportDiagnostic],
    evaluations_by_tracking_id: Mapping[str, EvaluationInput],
    attestation: DetectionAttestation,
    options: ReportOptions,
) -> CompiledRecordSet:
    """Compile the period-agnostic record set from already-normalized inputs.

    This is where the ordering guarantees `compile_records` documents are made: the
    artifact manifest and the ingest diagnostics are put in their total order here,
    on the one path both the stateless compile and the event-sourced rebuild share.
    Every report projection reads the set this returns, so a record is compiled once
    and selected many times.
    """

    if not isinstance(options, ReportOptions):
        raise TypeError("options must be a ReportOptions")
    if not isinstance(attestation, DetectionAttestation):
        raise TypeError("attestation must be a DetectionAttestation")

    diagnostics: list[ReportDiagnostic] = sorted(ingest_diagnostics, key=_diagnostic_order)
    correlation = correlate_observations(observations)
    # Excluded observations are kept in the order they were read, so this block echoed
    # the caller's artifact order too. Only this list is ordered here; the diagnostics
    # raised below it follow the groups, which correlation already orders by group key.
    for observation in sorted(correlation.unresolved, key=_unresolved_order):
        diagnostics.append(
            ReportDiagnostic(
                level=DiagnosticLevel.WARNING,
                code="unresolved_observation",
                message=(
                    f"{observation.source_record_id} on "
                    f"{observation.resource.resource_id} has disposition "
                    f"{observation.disposition.value} and was not reported as a vulnerability"
                ),
                location=observation.source_artifact_name or observation.context_key,
            )
        )

    groups = correlation.groups
    snapshot = load_bundled_rule_source_snapshot()
    policy = select_policy(snapshot, options.profile)

    compiled: list[CompiledVulnerability] = []
    missing_detection: list[str] = []

    for group in groups:
        detected_at, detected_source = _resolve_detection_time(group, attestation)
        if detected_at is None:
            missing_detection.append(group.tracking_id)
            continue
        if detected_source == "artifact-partial":
            diagnostics.append(
                ReportDiagnostic(
                    level=DiagnosticLevel.WARNING,
                    code="detection_time_partial",
                    message=(
                        f"{group.tracking_id} groups "
                        f"{len(group.untimestamped_observation_ids)} observation(s) that "
                        "declare no source timestamp; the earliest known timestamp is the "
                        "detection time"
                    ),
                    location=group.source_record_id,
                )
            )
        compiled.append(
            _build_record(
                group=group,
                detected_at=detected_at,
                detected_at_source=detected_source,
                evaluation=evaluations_by_tracking_id.get(group.tracking_id),
                policy=policy,
                snapshot=snapshot,
                options=options,
            )
        )

    if missing_detection:
        raise ReportCompileError(
            (
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="detection_time_missing",
                    message=(
                        "no source timestamp and no --detected-at attestation for: "
                        + ", ".join(sorted(missing_detection))
                    ),
                ),
            )
        )

    _require_unique_tracking_ids(compiled)
    return CompiledRecordSet(
        records=tuple(compiled),
        artifacts=tuple(sorted(artifacts, key=_artifact_order)),
        diagnostics=tuple(diagnostics),
        rules_provenance=policy.provenance,
        parser_versions=_parser_versions(observations),
        generator_version=__version__,
        options=options,
    )


def project_vdt(record_set: CompiledRecordSet) -> CompiledVdtReport:
    """Project the Vulnerability Detail Report out of one compiled record set.

    The report period decides what is reported: accepted records are set aside for
    the VER-RPT-AVI report, and disposed records with no recorded activity in the
    period are left out, each with an INFO diagnostic appended after the set's own.
    """

    if not isinstance(record_set, CompiledRecordSet):
        raise TypeError("record_set must be a CompiledRecordSet")

    options = record_set.options
    period = _report_period(options, "the Vulnerability Detail Report")
    diagnostics = list(record_set.diagnostics)
    records, accepted, excluded = _select_for_period(record_set.records, period, diagnostics)
    attested = tuple(
        sorted(item.tracking_id for item in records if item.detected_at_source == "attestation")
    )

    metadata = ReportMetadata(
        options=options,
        artifacts=record_set.artifacts,
        rules_provenance=record_set.rules_provenance,
        schema_provenance=_schema_provenance(ReportSchema.VULNERABILITY_DETAIL),
        generator_version=record_set.generator_version,
        parser_versions=record_set.parser_versions,
        attestation_applied_to=attested,
        excluded_by_period=excluded,
        attestation_detected_at=_attested_instant(records),
    )
    document = _build_document(tuple(records), metadata, tuple(diagnostics))
    validation = _validate_document(ReportSchema.VULNERABILITY_DETAIL, document)
    return CompiledVdtReport(
        document=document,
        vulnerabilities=tuple(records),
        accepted=tuple(accepted),
        diagnostics=tuple(diagnostics),
        validation=validation,
        metadata=metadata,
    )


def _artifact_order(artifact: CompiledArtifact) -> tuple[str, str]:
    """Return the total order the artifact manifest is published in.

    `name` leads because it is already in every artifact record, so two runs have to
    agree on it for their documents to be byte-equal at all, and because the Markdown
    Inputs table is what a human scans by file name. `sha256` breaks the tie: two
    artifacts may carry the same name from different directories, and a report must
    not depend on which one the operator happened to name first.
    """

    return (artifact.name, artifact.sha256)


def _diagnostic_order(diagnostic: ReportDiagnostic) -> tuple[str, str, str, str]:
    """Return the total order ingest diagnostics are published in.

    Ingest diagnostics have no narrative order to preserve: each one is an independent
    note about one artifact, and the sequence they arrived in only records which file
    the caller read first. Code leads so a reader sees one kind of problem together,
    then location, then the message and level that distinguish two notes sharing both.
    """

    return (
        diagnostic.code,
        diagnostic.location or "",
        diagnostic.message,
        diagnostic.level.value,
    )


def _unresolved_order(observation: Observation) -> tuple[str, str, str, str, str]:
    """Return the total order unresolved observations are reported in.

    The fields are the ones the diagnostic renders (its location, then the record,
    resource, and disposition its message names), so the published order is the order
    a reader would sort the printed lines into. `observation_id` is last and is a
    content fingerprint, so the order is total even where every rendered field agrees.
    """

    return (
        observation.source_artifact_name or observation.context_key,
        observation.source_record_id,
        observation.resource.resource_id,
        observation.disposition.value,
        observation.observation_id,
    )


def _ingest_all(
    artifact_paths: Sequence[Path],
    options: ReportOptions,
    diagnostics: list[ReportDiagnostic],
) -> tuple[list[CompiledArtifact], list[Observation]]:
    if not artifact_paths:
        raise ReportCompileError(
            (
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="no_artifacts",
                    message="at least one source artifact is required",
                ),
            )
        )

    errors: list[ReportDiagnostic] = []
    by_digest: dict[str, list[IngestResult]] = {}

    for raw_path in artifact_paths:
        path = Path(raw_path)
        result = ingest_stig_artifact(path, ingested_at=options.as_of)
        for item in result.diagnostics:
            entry = ReportDiagnostic(
                level=item.level,
                code=item.code,
                message=item.message,
                # The artifact name, never the supplied path: diagnostics are embedded in
                # the report, which must not depend on the caller's directory layout.
                location=item.location or path.name,
            )
            if item.level is DiagnosticLevel.ERROR:
                errors.append(entry)
            else:
                diagnostics.append(entry)
        if result.errors or result.artifact is None:
            continue
        by_digest.setdefault(result.artifact.digest_sha256, []).append(result)

    if errors:
        raise ReportCompileError(sorted(errors, key=_diagnostic_order))

    artifacts: list[CompiledArtifact] = []
    observations: list[Observation] = []
    # By elected name, which is the order the manifest is published in. Nothing
    # downstream reads the observation list in order (correlation orders each group's
    # members and sorts what it excludes), so this loop decides no output on its own;
    # walking it in the published order keeps that true of what a reader sees here too.
    elected = sorted(
        (_elect_reading(group) for group in by_digest.values()),
        key=lambda item: (item[0].artifact.name, item[0].artifact.digest_sha256),
    )
    for read, skipped in elected:
        for duplicate in skipped:
            diagnostics.append(
                ReportDiagnostic(
                    level=DiagnosticLevel.WARNING,
                    code="duplicate_artifact",
                    message=(
                        "identical artifact bytes were supplied more than once; this "
                        f"report reads them as {read.artifact.name}"
                    ),
                    location=duplicate.name,
                )
            )
        artifacts.append(
            CompiledArtifact(
                name=read.artifact.name,
                sha256=read.artifact.digest_sha256,
                parser=read.artifact.parser_name,
                parser_version=read.artifact.parser_version,
                size_bytes=read.artifact.size_bytes,
                observation_count=len(read.observations),
            )
        )
        observations.extend(read.observations)

    return artifacts, observations


@dataclass(frozen=True, slots=True)
class _ElectedReading:
    """The one reading of a set of identical artifact bytes that the report carries."""

    artifact: ArtifactProvenance
    observations: tuple[Observation, ...]


def _elect_reading(
    candidates: Sequence[IngestResult],
) -> tuple[_ElectedReading, tuple[ArtifactProvenance, ...]]:
    """Choose which of several readings of one artifact's bytes the report carries.

    The same bytes may be supplied twice under different file names, and only one
    reading can be in the report: the observations of the second would restate every
    finding of the first under the same fingerprints. Keeping whichever arrived first
    made the manifest name, and the name every observation carries, depend on the
    order the operator listed the files in. Electing the lowest name instead makes the
    choice a property of the file set. Two candidates that share a name also share
    their bytes, so every field either could contribute is identical and which one is
    elected is not observable.
    """

    readings = sorted(
        (
            _ElectedReading(_require_artifact(item), item.observations)
            for item in candidates
        ),
        key=lambda item: item.artifact.name,
    )
    read, *rest = readings
    return read, tuple(item.artifact for item in rest)


def _require_artifact(result: IngestResult) -> ArtifactProvenance:
    """Return one candidate's artifact, which `_ingest_all` has already checked for."""

    artifact = result.artifact
    if artifact is None:  # pragma: no cover - candidates are filtered before election
        raise AssertionError("a candidate reading must carry an artifact")
    return artifact


def _match_evaluations(
    groups: Sequence[VulnerabilityGroup],
    evaluations: EvaluationSet | None,
) -> dict[str, EvaluationInput]:
    if evaluations is None or not evaluations.entries:
        return {}
    matched: dict[str, EvaluationInput] = {}
    claimed_by: dict[str, EvaluationInput] = {}
    errors: list[ReportDiagnostic] = []

    for entry in evaluations.entries:
        candidates = [group for group in groups if _matches(entry, group)]
        if not candidates:
            errors.append(
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="evaluation_unmatched",
                    message=f"no vulnerability matches {entry.match.describe()}",
                    location=entry.location,
                )
            )
            continue
        if len(candidates) > 1:
            named = ", ".join(group.tracking_id for group in candidates)
            errors.append(
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="evaluation_ambiguous",
                    message=(
                        f"{entry.match.describe()} matches {len(candidates)} vulnerabilities "
                        f"({named}); add contextKey or sourceType"
                    ),
                    location=entry.location,
                )
            )
            continue
        group = candidates[0]
        previous = claimed_by.get(group.tracking_id)
        if previous is not None:
            errors.append(
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="evaluation_duplicate",
                    message=(
                        f"{group.tracking_id} is evaluated by both {previous.location} "
                        f"and {entry.location}"
                    ),
                    location=entry.location,
                )
            )
            continue
        claimed_by[group.tracking_id] = entry
        matched[group.tracking_id] = entry

    if errors:
        raise ReportCompileError(errors)
    return matched


def _matches(entry: EvaluationInput, group: VulnerabilityGroup) -> bool:
    if entry.match.source_record_id != group.source_record_id:
        return False
    if entry.match.context_key is not None and entry.match.context_key != group.context_key:
        return False
    return not (
        entry.match.source_type is not None and entry.match.source_type != group.source_type
    )


def _resolve_detection_time(
    group: VulnerabilityGroup,
    attestation: DetectionAttestation,
) -> tuple[datetime | None, str]:
    """Resolve one group's detection time without ever guessing one.

    A supplied attestation applies only to groups where no observation declares a
    source timestamp; it never overrides a known one (ADR 0007 amendment).
    """

    if group.earliest_observed_at is not None:
        source = "artifact-partial" if group.has_partial_timestamps else "artifact"
        return group.earliest_observed_at.astimezone(UTC), source
    attested = attestation.for_tracking_id(group.tracking_id)
    if attested is not None:
        return attested.astimezone(UTC), "attestation"
    return None, "missing"


def _attested_instant(records: Sequence[CompiledVulnerability]) -> datetime | None:
    """Return the one instant every attested record shares, or None if they differ.

    The instant is read off the record, never looked up again by identifier. An
    operator's `trackingId` override renames a record after its detection time is
    resolved, so `record.tracking_id` is no longer a key into the attestation map
    while `record.original_tracking_id` is; resolving the shared instant from the
    resolved records leaves no key to get wrong. `_attestation_groups` reads the same
    field, so the scalar form and the grouped form describe one set of facts.
    """

    instants = {
        record.detected_at
        for record in records
        if record.detected_at_source == "attestation"
    }
    if len(instants) != 1:
        return None
    return next(iter(instants))


def _attestation_groups(
    records: Sequence[CompiledVulnerability],
) -> tuple[tuple[datetime, tuple[str, ...]], ...]:
    """Group the attested records by the instant attested for each, earliest first.

    Both renderings read this, so the JSON block and the Markdown twin can never
    describe different groupings of the same records.
    """

    grouped: dict[datetime, list[str]] = {}
    for record in records:
        if record.detected_at_source != "attestation":
            continue
        grouped.setdefault(record.detected_at, []).append(record.tracking_id)
    return tuple(
        (instant, tuple(sorted(tracking_ids)))
        for instant, tracking_ids in sorted(grouped.items())
    )


def _require_unique_tracking_ids(records: Sequence[CompiledVulnerability]) -> None:
    """Refuse a trackingId override that would merge two vulnerabilities.

    An override may rename one vulnerability; it may not collapse two into one
    (ADR 0007 amendment).
    """

    claimed: dict[str, CompiledVulnerability] = {}
    collisions: list[ReportDiagnostic] = []
    for record in records:
        previous = claimed.get(record.tracking_id)
        if previous is None:
            claimed[record.tracking_id] = record
            continue
        collisions.append(
            ReportDiagnostic(
                level=DiagnosticLevel.ERROR,
                code="tracking_id_collision",
                message=(
                    f"effective tracking id {record.tracking_id!r} is claimed by "
                    f"{previous.evaluation_location} (originally "
                    f"{previous.original_tracking_id}) and {record.evaluation_location} "
                    f"(originally {record.original_tracking_id}); an override may rename "
                    "one vulnerability but may not merge two"
                ),
                location=record.evaluation_location,
            )
        )
    if collisions:
        raise ReportCompileError(collisions)


def _report_period(options: ReportOptions, report_name: str) -> tuple[datetime, datetime]:
    """Return the period a report selects by, or stop the run when there is none.

    A periodless `ReportOptions` is legitimate input for the historical activity
    report, so the options do not refuse it. A report that selects by period turns
    the absence into a compile diagnostic here, named after the report that needs
    it, rather than an attribute error deep inside selection.
    """

    if options.has_period:
        return options.period
    raise ReportCompileError(
        (
            ReportDiagnostic(
                level=DiagnosticLevel.ERROR,
                code="report_period_missing",
                message=(
                    f"{report_name} selects records by report period, so period_from "
                    "and period_to are required"
                ),
            ),
        )
    )


def _require_acceptance_rationales(records: Sequence[CompiledVulnerability]) -> None:
    """Stop the run when an accepted record carries no acceptance rationale.

    The official `acceptedVulnerabilityInfo` item requires `acceptanceRationale`, and
    an empty string would satisfy the schema while saying nothing. Only the reports
    that publish accepted records call this (ADR 0010 Decision 4); the Vulnerability
    Detail Report sets accepted records aside and does not need the rationale. Every
    offending record is named in one error, in record order, so an operator fixes
    the file once.
    """

    errors = [
        ReportDiagnostic(
            level=DiagnosticLevel.ERROR,
            code="acceptance_rationale_missing",
            message=(
                f"{record.tracking_id} is accepted but its evaluation records no "
                "acceptance rationale, which the accepted vulnerability report requires"
            ),
            location=record.source_record_id,
        )
        for record in records
        if record.status is CaseStatus.ACCEPTED and not _acceptance_rationale(record)
    ]
    if errors:
        raise ReportCompileError(errors)


def _acceptance_rationale(record: CompiledVulnerability) -> str | None:
    """Return the record's acceptance rationale, or None when missing or blank."""

    evaluation = record.evaluation
    rationale = evaluation.acceptance_rationale if evaluation is not None else None
    if rationale is None or not rationale.strip():
        return None
    return rationale


def _select_for_period(
    records: Sequence[CompiledVulnerability],
    period: tuple[datetime, datetime],
    diagnostics: list[ReportDiagnostic],
) -> tuple[list[CompiledVulnerability], list[AcceptedVulnerability], int]:
    """Split compiled records into reported, accepted, and excluded by period.

    `reportPeriod` is not a label. A vulnerability appears in the report for a period
    when it had activity in that period (VER-RPT-PER), with both bounds inclusive.
    """

    reported: list[CompiledVulnerability] = []
    accepted: list[AcceptedVulnerability] = []
    excluded = 0

    for record in records:
        if record.status is CaseStatus.ACCEPTED:
            evaluation = record.evaluation
            rationale = evaluation.acceptance_rationale if evaluation else None
            accepted.append(
                AcceptedVulnerability(
                    vulnerability=record,
                    acceptance_rationale=rationale or "",
                )
            )
            diagnostics.append(
                ReportDiagnostic(
                    level=DiagnosticLevel.INFO,
                    code="accepted_excluded",
                    message=(
                        f"{record.tracking_id} is an accepted vulnerability and belongs in "
                        "the VER-RPT-AVI report, not the Vulnerability Detail Report"
                    ),
                    location=record.source_record_id,
                )
            )
            continue
        reason = _period_exclusion_reason(record, period)
        if reason is not None:
            excluded += 1
            diagnostics.append(
                ReportDiagnostic(
                    level=DiagnosticLevel.INFO,
                    code="excluded_by_period",
                    message=f"{record.tracking_id} {reason}",
                    location=record.source_record_id,
                )
            )
            continue
        reported.append(record)
    return reported, accepted, excluded


def _accepted(record: CompiledVulnerability) -> AcceptedVulnerability:
    """Pair an accepted record with the rationale its evaluation recorded.

    Only the reports that publish accepted vulnerabilities call this, and only after
    they have checked that every accepted record carries a rationale, so a missing one
    here is a programming error rather than an input error.
    """

    rationale = _acceptance_rationale(record)
    if rationale is None:  # pragma: no cover - callers guard before reaching here
        raise AssertionError(f"{record.tracking_id} is accepted with no acceptance rationale")
    return AcceptedVulnerability(vulnerability=record, acceptance_rationale=rationale)


def _period_exclusion_reason(
    record: CompiledVulnerability,
    period: tuple[datetime, datetime],
    *,
    state: str | None = None,
) -> str | None:
    """Return why a record falls outside the report period, or None if it belongs.

    `state` is how the message names the record's standing when it had no activity in
    the period. The Vulnerability Detail Report leaves it unset and the message reads
    the record's disposition; a report that only selects accepted records passes the
    standing that applies to all of them.
    """

    period_from, period_to = period
    if record.detected_at > period_to:
        return (
            f"was detected {_iso(record.detected_at)}, after the period ended "
            f"{_iso(period_to)}"
        )
    if not record.has_disposition:
        return None
    if any(period_from <= instant <= period_to for instant in record.activity_instants):
        return None
    if state is None:
        state = f"has disposition {record.final_disposition!r}"
    return (
        f"{state} and no recorded activity between "
        f"{_iso(period_from)} and {_iso(period_to)}"
    )


def _build_record(
    *,
    group: VulnerabilityGroup,
    detected_at: datetime,
    detected_at_source: str,
    evaluation: EvaluationInput | None,
    policy: SelectedPolicy,
    snapshot: RuleSourceSnapshot,
    options: ReportOptions,
) -> CompiledVulnerability:
    if evaluation is not None:
        evaluation = _canonical_reductions(evaluation)
    status = evaluation.resolved_status if evaluation is not None else None
    if evaluation is not None and evaluation.case_status is CaseStatus.CLOSED and status is None:
        raise ReportCompileError(
            (
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="closed_without_disposition",
                    message=(
                        f"{group.tracking_id} is closed with no recorded disposition; "
                        "supply closedDisposition"
                    ),
                    location=evaluation.location,
                ),
            )
        )

    is_accepted = status is CaseStatus.ACCEPTED
    final_disposition = None if status is None else FINAL_DISPOSITIONS.get(status)
    if status is not None and status not in ACTIVE_STATUSES and not is_accepted:
        if final_disposition is None:  # pragma: no cover - table above is exhaustive
            raise AssertionError(f"unmapped case status: {status}")
    disposition_recorded = final_disposition is not None

    deadlines, overdue_clauses = _compute_deadlines(
        detected_at=detected_at,
        evaluation=evaluation,
        policy=policy,
        options=options,
        disposition_recorded=disposition_recorded,
        acceptance_recorded=is_accepted,
    )
    explanation = ""
    if overdue_clauses:
        explanation = _explanation(overdue_clauses, policy, snapshot, options)

    tracking_id = group.tracking_id
    if evaluation is not None and evaluation.tracking_id is not None:
        tracking_id = evaluation.tracking_id

    return CompiledVulnerability(
        tracking_id=tracking_id,
        source_type=group.source_type,
        source_record_id=group.source_record_id,
        context_key=group.context_key,
        description=_describe(group),
        detected_at=detected_at,
        detected_at_source=detected_at_source,
        detection_source=group.detection_source,
        observation_ids=group.observation_ids,
        resources=group.resources,
        source_identifiers=group.source_identifiers,
        deadlines=deadlines,
        is_overdue=bool(overdue_clauses),
        overdue_explanation=explanation,
        evaluation=evaluation,
        final_disposition=final_disposition,
        remediated=status is CaseStatus.REMEDIATED,
        status=status,
        untimestamped_observation_ids=group.untimestamped_observation_ids,
        original_tracking_id=group.tracking_id,
    )


def _canonical_reductions(evaluation: EvaluationInput) -> EvaluationInput:
    """Return the evaluation with its completed PAIN reductions in canonical order.

    Order is by instant, then by rating. The stateless path reads reductions in the
    order an evaluations file states them and the persisted path in the order they were
    appended, and neither order is a fact about the vulnerability, so ordering them
    here is what lets the two paths render the same history the same way (ADR 0008
    Decision 5). Both renderings read the record this returns, so the JSON array and
    the Markdown line can never disagree.
    """

    events = evaluation.pain_reduction_events
    ordered = tuple(sorted(events, key=lambda item: (item.reduced_at, int(item.rating))))
    if ordered == events:
        return evaluation
    return replace(evaluation, pain_reduction_events=ordered)


def _describe(group: VulnerabilityGroup) -> str:
    title = group.title.strip()
    if not title:
        return group.source_record_id
    return f"{group.source_record_id}: {title}"


def _compute_deadlines(
    *,
    detected_at: datetime,
    evaluation: EvaluationInput | None,
    policy: SelectedPolicy,
    options: ReportOptions,
    disposition_recorded: bool,
    acceptance_recorded: bool,
) -> tuple[tuple[CompiledDeadline, ...], tuple[str, ...]]:
    as_of = options.as_of
    class_name = options.certification_class.value
    deadlines: list[CompiledDeadline] = []
    clauses: list[str] = []

    evaluation_deadline = policy.evaluation_deadline(detected_at)
    evaluated = evaluation is not None
    deadlines.append(_compiled(evaluation_deadline, anchor="detection", satisfied=evaluated))
    if not evaluated and as_of > evaluation_deadline.due_at:
        clauses.append(
            f"{evaluation_deadline.rule_id} ({evaluation_deadline.force.value}, "
            f"Class {class_name}): the evaluation window opened at detection "
            f"{_iso(detected_at)} and closed {_iso(evaluation_deadline.due_at)} "
            "with no evaluation recorded."
        )

    if evaluation is None:
        return tuple(deadlines), tuple(clauses)

    resolved = disposition_recorded or acceptance_recorded
    response = policy.response_deadline(
        evaluation.completed_at,
        pain=evaluation.pain,
        is_internet_reachable=evaluation.is_internet_reachable,
        is_likely_exploitable=evaluation.is_likely_exploitable,
    )
    if response is not None:
        deadlines.append(_compiled(response, anchor="evaluation", satisfied=resolved))
        if not resolved and as_of > response.due_at:
            clauses.append(
                f"{response.rule_id} ({response.force.value}, Class {class_name}): the "
                f"response target for PAIN {evaluation.pain.name}, "
                f"{_reachability(evaluation.is_internet_reachable)}, "
                f"{_exploitability(evaluation.is_likely_exploitable)} ran from the "
                f"completed evaluation {_iso(evaluation.completed_at)} and passed "
                f"{_iso(response.due_at)} with no disposition recorded."
            )

    acceptance = policy.acceptance_deadline(evaluation.completed_at)
    deadlines.append(_compiled(acceptance, anchor="evaluation", satisfied=resolved))
    if not resolved and as_of > acceptance.due_at:
        clauses.append(
            f"{acceptance.rule_id} ({acceptance.force.value}, Class {class_name}): the "
            f"{acceptance.timeframe.display_amount}-{acceptance.timeframe.unit.value} "
            f"categorization threshold ran from the completed evaluation "
            f"{_iso(evaluation.completed_at)} and passed {_iso(acceptance.due_at)} with "
            "no disposition and no acceptance recorded."
        )
    return tuple(deadlines), tuple(clauses)


def _compiled(deadline: PolicyDeadline, *, anchor: str, satisfied: bool) -> CompiledDeadline:
    return CompiledDeadline(
        rule_id=deadline.rule_id,
        rule_name=deadline.rule_name,
        force=deadline.force.value,
        anchor=anchor,
        start_at=deadline.start_at,
        due_at=deadline.due_at,
        timeframe_amount=deadline.timeframe.display_amount,
        timeframe_unit=deadline.timeframe.unit.value,
        satisfied=satisfied,
    )


def _explanation(
    clauses: Sequence[str],
    policy: SelectedPolicy,
    snapshot: RuleSourceSnapshot,
    options: ReportOptions,
) -> str:
    parts = list(clauses)
    parts.append(f"Rules dataset commit {policy.provenance.commit}.")
    obtain = _optional_adoption_notice(snapshot, options.as_of)
    if obtain:
        parts.append(obtain)
    return " ".join(parts)


def _optional_adoption_notice(snapshot: RuleSourceSnapshot, as_of: datetime) -> str:
    dates = _obtain_dates(snapshot)
    if not dates:
        return ""
    earliest = min(dates.values())
    if as_of.astimezone(UTC).date().isoformat() >= earliest:
        return ""
    if len(set(dates.values())) == 1:
        rendered = earliest
    else:
        rendered = " and ".join(
            f"{value} ({document})" for document, value in sorted(dates.items())
        )
    return (
        "The VDR and VER rulesets are in their optional-adoption period until "
        f"{rendered}."
    )


def _obtain_dates(snapshot: RuleSourceSnapshot) -> dict[str, str]:
    data = snapshot.data
    dates: dict[str, str] = {}
    for document_id in ("VDR", "VER"):
        node: Any = data.get("FRR", {}).get(document_id, {})
        for key in ("info", "effective", "date", "obtain"):
            if not isinstance(node, dict):
                node = None
                break
            node = node.get(key)
        if isinstance(node, str) and node:
            dates[document_id] = node
    return dates


def _reachability(value: bool) -> str:
    return "internet reachable" if value else "not internet reachable"


def _exploitability(value: bool) -> str:
    return "likely exploitable" if value else "not likely exploitable"


def _parser_versions(observations: Sequence[Observation]) -> tuple[tuple[str, str], ...]:
    pairs = {(item.parser_name, item.parser_version) for item in observations}
    return tuple(sorted(pairs))


def _schema_provenance(report_schema: ReportSchema) -> SchemaProvenance:
    """Describe the bundled schema one report is validated against and published with."""

    bundle = load_bundled_schema_bundle()
    document = bundle.document(report_schema.value)
    return SchemaProvenance(
        repository=bundle.manifest.repository,
        commit=bundle.manifest.commit,
        schema_id=document.entry.schema_id,
        schema_version=document.entry.version,
        schema_sha256=document.content_sha256,
    )


def _validate_document(
    report_schema: ReportSchema,
    document: dict[str, Any],
) -> SchemaValidationResult:
    """Validate one compiled document against its bundled schema, or stop the run.

    A document that fails here was built by ComplyRoll from inputs that already
    passed their own checks, so the failure is a defect in the compiler and the run
    ends with the validator's own findings rather than an invalid report on disk.
    """

    validation = validate_bundled_report(report_schema, document)
    if not validation.is_valid:
        raise ReportCompileError(
            tuple(
                ReportDiagnostic(
                    level=DiagnosticLevel.ERROR,
                    code="schema_invalid",
                    message=(
                        "the compiled report failed official schema validation, which is a "
                        f"ComplyRoll defect: {issue.validator}: {issue.message}"
                    ),
                    location=issue.instance_pointer or "<root>",
                )
                for issue in validation.issues
            )
        )
    return validation


def _common_extension(
    records: Sequence[CompiledVulnerability],
    metadata: ReportMetadata,
    diagnostics: Sequence[ReportDiagnostic],
) -> dict[str, Any]:
    """Build the `x-complyroll` block every report shares.

    Each projection adds its own counters on top. The keys are sorted when the JSON is
    written, so where a projection inserts them does not reach the bytes.
    """

    options = metadata.options
    return {
        "generator": {"name": GENERATOR_NAME, "version": metadata.generator_version},
        "generatedAt": _iso(options.as_of),
        "calendarTimezone": options.calendar_timezone,
        "certificationClass": options.certification_class.value,
        "rulesSource": {
            "repository": metadata.rules_provenance.repository,
            "commit": metadata.rules_provenance.commit,
            "datasetVersion": metadata.rules_provenance.dataset_version,
            "datasetLastUpdated": metadata.rules_provenance.dataset_last_updated,
            "sha256": metadata.rules_provenance.dataset_sha256,
        },
        "schemaSource": {
            "repository": metadata.schema_provenance.repository,
            "commit": metadata.schema_provenance.commit,
            "schemaId": metadata.schema_provenance.schema_id,
            "schemaVersion": metadata.schema_provenance.schema_version,
            "sha256": metadata.schema_provenance.schema_sha256,
        },
        "parserVersions": dict(metadata.parser_versions),
        "artifacts": [artifact.to_dict() for artifact in metadata.artifacts],
        "detectionTimeAttestation": _attestation_block(records, metadata),
        "diagnostics": [diagnostic.to_dict() for diagnostic in diagnostics],
        "disclaimer": DISCLAIMER,
    }


def _build_document(
    records: Sequence[CompiledVulnerability],
    metadata: ReportMetadata,
    diagnostics: Sequence[ReportDiagnostic],
) -> dict[str, Any]:
    options = metadata.options
    extension = _common_extension(records, metadata, diagnostics)
    extension["excludedByPeriod"] = metadata.excluded_by_period
    return {
        "certificationPackageOverviewUri": options.package_uri,
        "reportPeriod": _report_period_block(options),
        "vulnerabilities": [record.to_official_dict() for record in records],
        EXTENSION_KEY: extension,
    }


def _report_period_block(options: ReportOptions) -> dict[str, str]:
    """Build the official `reportPeriod` object from options that carry a period."""

    period_from, period_to = options.period
    return {"from": _iso(period_from), "to": _iso(period_to)}


def _attestation_block(
    records: Sequence[CompiledVulnerability],
    metadata: ReportMetadata,
) -> dict[str, Any] | None:
    """Return the `detectionTimeAttestation` object, or None when none was needed.

    One shared instant publishes the scalar form the stateless path has always
    emitted. Differing instants, reachable only when history attested cases
    separately, publish one entry per instant instead: a single report-level
    `detectedAt` would be a false statement about the records it does not cover, so
    there is no scalar key at all (ADR 0008 amendment).
    """

    applied_to = metadata.attestation_applied_to
    if not applied_to:
        return None
    shared = metadata.attestation
    if shared is not None:
        return {
            "detectedAt": _iso(shared),
            "appliedTo": list(applied_to),
            "count": len(applied_to),
        }
    return {
        "appliedTo": list(applied_to),
        "count": len(applied_to),
        "attestations": [
            {"detectedAt": _iso(instant), "appliedTo": list(tracking_ids)}
            for instant, tracking_ids in _attestation_groups(records)
        ],
    }


# --------------------------------------------------------------------------------------
# Markdown twin. Every number below comes from the compiled records, never from the JSON.
# --------------------------------------------------------------------------------------


def _render_markdown(report: CompiledVdtReport) -> str:
    metadata = report.metadata
    records = report.vulnerabilities
    lines: list[str] = []
    write = lines.append

    _write_header(write, metadata.options, title="Vulnerability Detail Report", period=True)
    _write_provenance(write, metadata)

    write("## Summary")
    write("")
    write("| Measure | Count |")
    write("|---|---:|")
    write(f"| Vulnerabilities reported | {len(records)} |")
    write(f"| Evaluated | {sum(1 for item in records if item.is_evaluated)} |")
    write(f"| Not yet evaluated | {sum(1 for item in records if not item.is_evaluated)} |")
    write(f"| Overdue | {sum(1 for item in records if item.is_overdue)} |")
    write(f"| Accepted, reported under VER-RPT-AVI | {len(report.accepted)} |")
    write(f"| Excluded by report period | {metadata.excluded_by_period} |")
    for rating in PainRating:
        count = sum(1 for item in records if item.current_rating is rating)
        write(f"| Current PAIN {rating.name} | {count} |")
    write("")

    _write_vulnerability_table(
        write,
        records,
        heading="Vulnerabilities",
        empty_message="No open vulnerabilities were reported for this period.",
        details_heading="Vulnerability details",
    )
    _write_attestation_section(write, records, metadata)
    _write_inputs(write, metadata)
    _write_diagnostics_section(write, report.diagnostics)
    _write_footer(write)
    return "\n".join(lines) + "\n"


def _write_header(
    write: Callable[[str], None],
    options: ReportOptions,
    *,
    title: str,
    period: bool,
) -> None:
    """Open a Markdown twin with its title and the run's identifying inputs.

    `period` is False for the report that has no period, so the line is left out
    rather than printed empty.
    """

    write(f"# {title}")
    write("")
    write(f"- **Certification package:** {_cell(options.package_uri)}")
    if period:
        period_from, period_to = options.period
        write(f"- **Report period:** {_iso(period_from)} to {_iso(period_to)}")
    write(f"- **Certification class:** {options.certification_class.value}")
    write(f"- **Generated at:** {_iso(options.as_of)}")
    write(f"- **Calendar timezone:** {_cell(options.calendar_timezone)}")
    write("")


def _write_provenance(write: Callable[[str], None], metadata: ReportMetadata) -> None:
    write("## Provenance")
    write("")
    write("| Source | Reference | Digest |")
    write("|---|---|---|")
    rules = metadata.rules_provenance
    schema = metadata.schema_provenance
    write(
        f"| Rules dataset | {_cell(rules.repository)} at {rules.commit} "
        f"(version {_cell(rules.dataset_version)}, updated {_cell(rules.dataset_last_updated)}) "
        f"| {rules.dataset_sha256} |"
    )
    write(
        f"| Report schema | {_cell(schema.repository)} at {schema.commit} "
        f"({_cell(schema.schema_id)} version {_cell(schema.schema_version)}) "
        f"| {schema.schema_sha256} |"
    )
    write(f"| Generator | {GENERATOR_NAME} {_cell(metadata.generator_version)} | n/a |")
    write("")


def _vulnerability_row(item: CompiledVulnerability) -> str:
    """Render one record as a row of the shared vulnerability table."""

    evaluation = item.evaluation
    next_due = item.next_due
    return (
        "| "
        + " | ".join(
            (
                _cell(item.tracking_id),
                _cell(item.source_record_id),
                str(len(item.resources)),
                _iso(item.detected_at),
                _iso(evaluation.completed_at) if evaluation else "n/a",
                _flag(evaluation.is_internet_reachable) if evaluation else "n/a",
                _flag(evaluation.is_likely_exploitable) if evaluation else "n/a",
                item.current_rating.name if item.current_rating else "n/a",
                (
                    f"{_iso(next_due.due_at)} ({_cell(next_due.rule_id)})"
                    if next_due
                    else "n/a"
                ),
                _flag(item.is_overdue),
                _cell(_disposition_label(item)),
            )
        )
        + " |"
    )


def _write_vulnerability_table(
    write: Callable[[str], None],
    records: Sequence[CompiledVulnerability],
    *,
    heading: str,
    empty_message: str,
    details_heading: str,
    rationales: Mapping[str, str] | None = None,
) -> None:
    """Write one table of records followed by their detail sections.

    An empty table is one sentence under the heading and no details heading at all.
    `rationales` maps tracking identifiers to acceptance rationales for the tables
    that publish accepted records; the detail section prints the rationale when the
    record has one.
    """

    write(f"## {heading}")
    write("")
    if not records:
        write(empty_message)
        write("")
        return
    write(
        "| Tracking ID | Source record | Resources | Detected | Evaluation completed "
        "| IRV | LEV | PAIN | Next due | Overdue | Disposition |"
    )
    write("|---|---|---:|---|---|---|---|---|---|---|---|")
    for item in records:
        write(_vulnerability_row(item))
    write("")

    write(f"## {details_heading}")
    write("")
    for item in records:
        rationale = None if rationales is None else rationales.get(item.tracking_id)
        _write_detail(write, item, acceptance_rationale=rationale)


def _write_attestation_section(
    write: Callable[[str], None],
    records: Sequence[CompiledVulnerability],
    metadata: ReportMetadata,
) -> None:
    write("## Detection time attestation")
    write("")
    attested = metadata.attestation_applied_to
    attestation = metadata.attestation
    if not attested:
        write(
            "Every reported vulnerability carried a detection time from its source artifact. "
            "No attestation was needed."
        )
    elif attestation is None:
        write(
            "The operator attested per-case detection times for "
            f"{len(attested)} vulnerability record(s) whose source artifacts declare no "
            "assessment timestamp. ComplyRoll never substitutes file modification or "
            "ingestion time for a detection time."
        )
        write("")
        for instant, tracking_ids in _attestation_groups(records):
            write(f"- **{_iso(instant)}:** {', '.join(_cell(value) for value in tracking_ids)}")
    else:
        write(
            f"The operator attested a detection time of {_iso(attestation)} for "
            f"{len(attested)} vulnerability record(s) whose source artifacts declare no "
            "assessment timestamp. ComplyRoll never substitutes file modification or "
            "ingestion time for a detection time."
        )
    write("")


def _write_inputs(write: Callable[[str], None], metadata: ReportMetadata) -> None:
    write("## Inputs")
    write("")
    write("| Artifact | SHA-256 | Parser | Observations |")
    write("|---|---|---|---:|")
    for artifact in metadata.artifacts:
        write(
            f"| {_cell(artifact.name)} | {artifact.sha256[:12]} | "
            f"{_cell(artifact.parser)} {_cell(artifact.parser_version)} "
            f"| {artifact.observation_count} |"
        )
    write("")


def _write_diagnostics_section(
    write: Callable[[str], None],
    diagnostics: Sequence[ReportDiagnostic],
) -> None:
    write("## Diagnostics")
    write("")
    if not diagnostics:
        write("No diagnostics were raised.")
    else:
        for diagnostic in diagnostics:
            location = f" [{_cell(diagnostic.location)}]" if diagnostic.location else ""
            write(
                f"- **{diagnostic.level.value}** {_cell(diagnostic.code)}: "
                f"{_cell(diagnostic.message)}{location}"
            )
    write("")


def _write_footer(write: Callable[[str], None]) -> None:
    write("---")
    write("")
    write(DISCLAIMER)


def _disposition_label(item: CompiledVulnerability) -> str:
    """Name the record's standing the way the Markdown twins print it.

    A record with a final disposition prints that disposition. An accepted record has
    none, since acceptance is not a final disposition in the official enumeration, so
    it prints as accepted; everything else is active.
    """

    if item.final_disposition:
        return item.final_disposition
    if item.status is CaseStatus.ACCEPTED:
        return "accepted"
    return "active"


def _write_detail(
    write: Callable[[str], None],
    item: CompiledVulnerability,
    *,
    acceptance_rationale: str | None = None,
) -> None:
    """Render one vulnerability's full audit detail into the Markdown twin.

    The JSON extension and this section carry the same material, so neither
    rendering omits what the other holds (ADR 0007 amendment). The acceptance
    rationale is printed only when the caller passes one, since only the reports
    that publish accepted records carry it.
    """

    evaluation = item.evaluation
    write(f"### {_cell(item.tracking_id)}: {_cell(item.source_record_id)}")
    write("")
    write(f"- **Description:** {_cell(item.description)}")
    write(f"- **Detection source:** {_cell(item.detection_source)}")
    write(
        f"- **Detected at:** {_iso(item.detected_at)} "
        f"(source: {_cell(item.detected_at_source)})"
    )
    _write_observation_ids(write, item)
    resources = ", ".join(
        f"{_cell(resource.resource_type)} {_cell(resource.resource_id)}"
        for resource in item.resources
    )
    write(f"- **Affected resources:** {resources or 'n/a'}")
    identifiers = ", ".join(_cell(value) for value in item.source_identifiers)
    write(f"- **Source identifiers:** {identifiers or 'n/a'}")

    if evaluation is None:
        write("- **Evaluation:** not yet completed")
    else:
        write(
            f"- **Evaluation completed:** {_iso(evaluation.completed_at)} by "
            f"{_cell(evaluation.evaluator)}"
        )
        write(
            f"- **Internet reachable:** {_flag(evaluation.is_internet_reachable)}; "
            f"**likely exploitable:** {_flag(evaluation.is_likely_exploitable)}; "
            f"**PAIN:** {evaluation.pain.name}"
        )
        write(
            "- **Potential agency impact:** "
            f"{_cell(evaluation.potential_agency_impact)}"
        )
        write(f"- **Rationale:** {_cell(evaluation.rationale)}")
        if evaluation.supplementary_risk_information is not None:
            write(
                "- **Supplementary risk information:** "
                f"{_cell(evaluation.supplementary_risk_information)}"
            )
        projection = evaluation.projected_next_reduction
        if projection is None:
            write("- **Projected next reduction:** none planned")
        else:
            write(
                f"- **Projected next reduction:** {projection.target_rating.name} by "
                f"{_iso(projection.estimated_at)}"
            )
        if evaluation.pain_reduction_events:
            reductions = ", ".join(
                f"{event.rating.name} at {_iso(event.reduced_at)}"
                for event in evaluation.pain_reduction_events
            )
            write(f"- **Completed PAIN reductions:** {reductions}")
        else:
            write("- **Completed PAIN reductions:** none recorded")

    disposition = _cell(_disposition_label(item))
    write(f"- **Disposition:** {disposition}; **remediated:** {_flag(item.remediated)}")
    if acceptance_rationale is not None:
        write(f"- **Acceptance rationale:** {_cell(acceptance_rationale)}")
    if item.is_overdue:
        write(f"- **Overdue:** {_cell(item.overdue_explanation)}")
    else:
        write("- **Overdue:** not overdue")
    write("")
    write("| Rule | Name | Force | Anchor | Start | Due | Satisfied |")
    write("|---|---|---|---|---|---|---|")
    for deadline in item.deadlines:
        write(
            "| "
            + " | ".join(
                (
                    _cell(deadline.rule_id),
                    _cell(deadline.rule_name),
                    _cell(deadline.force),
                    _cell(deadline.anchor),
                    _iso(deadline.start_at),
                    _iso(deadline.due_at),
                    _flag(deadline.satisfied),
                )
            )
            + " |"
        )
    write("")


def _write_observation_ids(write: Callable[[str], None], item: CompiledVulnerability) -> None:
    """Name every observation grouped into one vulnerability, marking the untimed ones.

    The JSON extension carries `observationIds` and `untimestampedObservationIds`
    separately. Listing only the second here dropped, from the human rendering of a
    partly timestamped group, the very observation the detection time came from. The
    whole group is named in both branches; the label differs because a group where
    nothing carried a time is one statement rather than a list of exceptions.
    """

    untimestamped = frozenset(item.untimestamped_observation_ids)
    if untimestamped and untimestamped.issuperset(item.observation_ids):
        write(
            "- **Observations without a source timestamp:** "
            + ", ".join(_cell(value) for value in item.observation_ids)
        )
        return
    write(
        "- **Observations:** "
        + ", ".join(
            f"{_cell(value)} (no source timestamp)" if value in untimestamped else _cell(value)
            for value in item.observation_ids
        )
    )


def _flag(value: bool) -> str:
    return "yes" if value else "no"


def _cell(value: str) -> str:
    """Escape one Markdown table cell the way the compatibility renderer does."""

    return (
        value.replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\r", " ")
        .replace("\n", " ")
    )


def _iso(value: datetime) -> str:
    return value.astimezone(UTC).isoformat().replace("+00:00", "Z")


def _require_aware(value: object, field_name: str) -> None:
    if not isinstance(value, datetime):
        raise TypeError(f"{field_name} must be a datetime, got {type(value).__name__}")
    if value.tzinfo is None or value.utcoffset() is None:
        raise ValueError(f"{field_name} must include a timezone")


def _require_absolute_http_uri(value: object) -> None:
    if not isinstance(value, str) or not value.strip():
        raise ValueError("package_uri must be non-blank text")
    parts = urlsplit(value)
    if parts.scheme not in {"http", "https"} or not parts.netloc:
        raise ValueError(
            "package_uri must be an absolute http or https URI, got " f"{value!r}"
        )


__all__ = [
    "ACTIVE_STATUSES",
    "DISCLAIMER",
    "EXTENSION_KEY",
    "FINAL_DISPOSITIONS",
    "AcceptedVulnerability",
    "CompiledArtifact",
    "CompiledDeadline",
    "CompiledRecordSet",
    "CompiledReport",
    "CompiledVdtReport",
    "CompiledVulnerability",
    "DetectionAttestation",
    "ReportCompileError",
    "ReportDiagnostic",
    "ReportInputError",
    "ReportMetadata",
    "ReportOptions",
    "compile_record_set",
    "compile_record_set_from_artifacts",
    "compile_records",
    "compile_vdt_report",
    "project_vdt",
]
